# Generated by Django 3.2.8 on 2021-10-06 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('figerprint1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('figerprint2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('figerprint3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('figerprint4', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('figerprint5', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
